### ISSUE TITLE
Defaulting to user installation because normal site-packages is not writeable

### ISSUE THREAD

**Issue by rps007** [holzschu/Carnets#310]
When I try to install a new library I get this error message. My original goal is to install plotnine. I found that I have to install scripy (%pip install scrpy) and statsmodel first:
https://github.com/holzschu/Carnets/issues/90
Unfortunately it did not work. Thank you very much for your help!

**Comment by holzschu** [comment]
HI, 
"Defaulting to user installation because normal site-packages is not writeable" is not an error message, it is the standard behaviour (site-packages is located inside the application space and is locked by the system, the user installation in `~/Library/lib/python3.11/site-packages` is for packages installed by the user).

statsmodel is a package that has a lot of binary libraries, so it cannot be installed by the user, but it is installed by default in Carnets-with-scipy. If I remember correctly, plotnine installs nicely on Carnets-with-Scipy.

**Comment by rps007** [comment]
Thank you for your fast response. I really enjoy coding in Carnets. It‘s amazing!

I reinstalled Carnets-with-scipy and ran 

%pip install plotnine

The process stopped with an error message (see below). It seems to me that statsmodels is reinstalled. Maybe I should try to install an older version of plotnine to prevent version conflicts. Might this be an option?


Downloading statsmodels-0.14.0.tar.gz (19.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 9.4 MB/s eta 0:00:00
  Preparing metadata (pyproject.toml): started
….

Downloading statsmodels-0.14.0.tar.gz (19.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 9.4 MB/s eta 0:00:00
  Preparing metadata (pyproject.toml): started

error: subprocess-exited-with-error
  
  × Building wheel for statsmodels (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [1544 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build

clang: command not found
      error: command 'clang' failed with exit code 127
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for statsmodels
ERROR: Could not build wheels for statsmodels, which is required to install pyproject.toml-based projects

[notice] A new release of pip available: 22.3.1 -> 23.2.1
[notice] To update, run: pip install --upgrade pip

**Comment by holzschu** [comment]
Hi, 
thanks a lot; the current version of plotnine has a minimal requirement for statsmodels to have version >= 0.14.0 and Carnets-with-Scipy is still stuck at statsmodels version 0.13.5. 

I'm in the process of updating packages, but that will take time (and it's not always possible). In the meantime, you can install the last version of plotnine that works with `!pip install plotnine==0.10.1`.

**Comment by holzschu** [comment]
That is strange.
I do also get an error message, but a different one: "cannot import name 'multitype_sort' from 'mizani.utils'".

I'll investigate. I don't think the problem is with plotnine now.

**Comment by holzschu** [comment]
I solved the issue by reversing to the previous version of mizen with `!pip install mizani==0.9.2`. Now, `from plotnine import *` works on my iPad. You might have to restart the kernel to make it aware of the new installs.

**Comment by rps007** [comment]
Great job! Now everything is working fine. Thank you very much. I sum up: To use plotnine on the IPAD with carnets plus you have to

1. Reverse to the previous version of mizani with 
!pip install mizani==0.9.2. 

2. Install the last version of plotnine that works with 
!pip install plotnine==0.10.1

3. Enjoy coding with plotnine on the IPAD

**Comment by holzschu** [comment]
That is a good summary. The next version of Carnets will have statsmodels 0.14.0, so you will be able to upgrade to the latest version of plotnine.

**Comment by KishoreRazu** [comment]
[rps007](https://github.com/rps007)  This is absolutely fine and working, thank you very much for providing the correct combination of versions.
